### ISSUE TITLE
sudo npm run dev error

### ISSUE THREAD

**Issue by huillll** [limingcun/FoodTraceability#2]
> szy@ dev /home/luhui/FoodTraceability
> cross-env NODE_ENV=development webpack-dev-server --inline --hot

/home/luhui/FoodTraceability/node_modules/webpack/lib/NormalModuleFactory.js:72
			var elements = request.replace(/^-?!+/, "").replace(/!!+/g, "!").split("!");
			                       ^

TypeError: Cannot read property 'replace' of undefined
    at /home/luhui/FoodTraceability/node_modules/webpack/lib/NormalModuleFactory.js:72:27
    at /home/luhui/FoodTraceability/node_modules/webpack/lib/NormalModuleFactory.js:28:4
    at /home/luhui/FoodTraceability/node_modules/webpack/lib/NormalModuleFactory.js:159:3
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/home/luhui/FoodTraceability/node_modules/tapable/lib/Tapable.js:75:69)
    at NormalModuleFactory.create (/home/luhui/FoodTraceability/node_modules/webpack/lib/NormalModuleFactory.js:144:8)
    at /home/luhui/FoodTraceability/node_modules/webpack/lib/Compilation.js:214:11
    at /home/luhui/FoodTraceability/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (/home/luhui/FoodTraceability/node_modules/async/lib/async.js:233:13)
    at Object.async.forEach.async.each (/home/luhui/FoodTraceability/node_modules/async/lib/async.js:209:22)
    at Compilation.addModuleDependencies (/home/luhui/FoodTraceability/node_modules/webpack/lib/Compilation.js:185:8)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! szy@ dev: `cross-env NODE_ENV=development webpack-dev-server --inline --hot`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the szy@ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/luhui/.npm/_logs/2020-03-30T09_45_17_697Z-debug.log

**Comment by huillll** [comment]
node -v
v12.16.1

希望可以联系你，有偿解决。qq:2842364244
